### ISSUE TITLE
Exception when Triggers added on both Parent and Child class

### ISSUE THREAD

**Issue by ConradPoohs** [NickStrupat/EntityFramework.Triggers#1] opened 2015-02-15 01:13 UTC
Trying to add Triggers in both a parent (`CreatedEntity`) and child (`ModifiedCreatedEntity`) class, but I keep hitting an `InvalidCastException` (details below) on `context.SaveChanges()`

Moving both the triggers to either the parent or child class resolves the problem, but isn't as nice design-wise, since I would like some entity classes to inherit from the parent (with its properties and associated triggers) and other entity classes to inherit from the child (with both the parent and child properties and triggers). Any help or advice would be greatly appreciated.
### Sample Code:

``` C#
using System;
using System.Data.Entity;
using EntityFramework.Triggers;

class CreatedEntity : ITriggerable
{
    public CreatedEntity()
    {
        this.Triggers().Inserting += entry => { entry.Entity.InsertedDateTime = DateTime.Now; };
    }
    public DateTime InsertedDateTime { get; set; }

}

class ModifiedCreatedEntity : CreatedEntity
{
    public ModifiedCreatedEntity()
    {
        //this.Triggers().Inserting += entry => { entry.Entity.InsertedDateTime = DateTime.Now; };
        this.Triggers().Inserting += entry => { entry.Entity.ModifiedDateTime = DateTime.Now; };
        this.Triggers().Updating += entry => { entry.Entity.ModifiedDateTime = DateTime.Now; };
    }
    public Int64 Id { get; protected set; }
    public DateTime ModifiedDateTime { get; set; }

}

class Context : DbContext
{
    public DbSet<ModifiedCreatedEntity> Entities { get; set; }

    public override Int32 SaveChanges() { return this.SaveChangesWithTriggers(base.SaveChanges); }
}

class Program
{


    static void Main(string[] args)
    {
        using (var context = new Context())
        {
            try
            {
                var entity = new ModifiedCreatedEntity();
                context.Entities.Add(entity);
                context.SaveChanges();
            }
            finally
            {
                context.Database.Delete();
            }
        }
    }
}
```
### Exception:

``` C#
System.InvalidCastException was unhandled
  HResult=-2147467262
  Message=Unable to cast object of type 'EntityFramework.Triggers.Triggers`1[CreatedEntity]' to type 'EntityFramework.Triggers.Triggers`1[ModifiedCreatedEntity]'.
  Source=EntityFramework.Triggers
  StackTrace:
       at EntityFramework.Triggers.Extensions.Triggers[TTriggerable](TTriggerable triggerable) in c:\Development\EntityFramework.Triggers\EntityFramework.Triggers\Extensions.cs:line 27
       at ModifiedCreatedEntity..ctor() in c:\Users\user\Documents\Visual Studio 2013\Projects\TriggerTestApp\TriggerTestApp\Program.cs:line 20
       at Program.Main(String[] args) in c:\Users\user\Documents\Visual Studio 2013\Projects\TriggerTestApp\TriggerTestApp\Program.cs:line 45
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by NickStrupat** [comment] 2015-02-16 00:16
Thanks for the input.

I have some code that does this same thing, and it seems to be broken with this version which means there was a regression. I designed it to handle this situation, and I've obviously overlooked something. I'm looking at the code now.

**Comment by NickStrupat** [comment] 2015-02-16 10:49
@ConradPoohs I have pushed a fix to the master branch, as well as the appropriate test to make sure it doesn't break base class triggers again. Please do a pull on your clone or update your NuGet package. Enjoy!

**Comment by ConradPoohs** [comment] 2015-02-17 02:52
Got the updated package and the inherited triggers exactly as designed now. Thank you so much for the quick fix!

**Closed as completed** 2015-02-17 23:12 UTC
